### ISSUE TITLE
Weird behaviour with V1 query API

### ISSUE THREAD

**Issue by cookstaar** [walkerrandolphsmith/VersionOne.SDK.JavaScript.Example#1]
Hey. Not directly related to your repo but thought you may be able to shed some light as you seem to be one of the few people who have any content on the V1 JS SDK. Following your example using Axios, I can see that  V1.query is using a HTTP GET, and therefore returns an empty dataset as it is not passing the query data.

Any ideas. I have stepped through the code but have no idea where its going wrong. Thanks in advance for any help you can provide. 

Neil

**Comment by walkerrandolphsmith** [comment]
`query` uses the query.v1 VersionOne api and should use an HTTP POST method as you have indicated. Looking at the VersionOne.SDK.JavaScript repo, https://github.com/versionone/VersionOne.SDK.JavaScript/blob/13e6edfd8484e10762abf975cad0f7c3403e28c1/src/createMeta.js#L37 it seems to indicate `query` uses `postFn`. Based on the axios connector we are using the `postFn` should look like this https://github.com/versionone/VersionOne.SDK.JavaScript/blob/13e6edfd8484e10762abf975cad0f7c3403e28c1/src/connectors/axiosConnector.js#L3. I'd love to help. Do you have an example or is this repo the example?

**Comment by cookstaar** [comment]
Basically used this repo. I debugged through and it looked like it returned postFn(.....), but then when I looked at response from the V1 API it was responding to a GET and hence returned an empty array in Data.

I'm out and about at the moment but will try to post some more details when I get home.

Thanks for your help!

**Comment by cookstaar** [comment]
Yep, tried again and cant get it to work. My first attempt was to just npm init a new project and then pull in axios & v1sdk. When doing that it makes a GET call.

If I clone your repo & then npm install on it them it doesnt seem to work at all........just goes away and never comes back.

But if I just use the raw axios library then everything works just fine. Confused.......

**Comment by walkerrandolphsmith** [comment]
If you clone this repo you will need to update `V1Server.js` with your VersionOne instance information including: https://github.com/walkerrandolphsmith/sample-v1sdk-app/blob/704028ada5ed80411a351e20843c57668f3743dd/V1Server.js#L7. Can you point me to the repo you are working on so I can take a look? Also I may be available to pair program to work through your issues if you are interested.

**Comment by cookstaar** [comment]
Yeah this is all im working with. https://github.com/cookstaar/v1-sdk-debugging

Im running on Windows, doubt its significant but you never know.......

**Comment by walkerrandolphsmith** [comment]
```
const axios = require('axios');
const v1sdk = require('v1sdk/dist/index');
const sdk = v1sdk.default;
const axiosConnector = v1sdk.axiosConnector;

const axiosConnectedSdk = axiosConnector(axios)(sdk);
const v1 = axiosConnectedSdk('www14.v1host.com', 'v1sdktesting')
    //.withCreds('v1User', 'v1Password');
    .withAccessToken('1.MVciNffaAPeD1GBAYb86JrAbACU=');

v1.query({
    'from': 'Story', 
    'select': ['Name']
}).then(function (response) {
    console.log(response.config)
    console.log(response.data);
})
.catch(function (error) {
    console.log(error);
});
```

Provides the following logging: 
```
{ adapter: [Function: httpAdapter],
  transformRequest: { '0': [Function: transformRequest] },
  transformResponse: { '0': [Function: transformResponse] },
  timeout: 0,
  xsrfCookieName: 'XSRF-TOKEN',
  xsrfHeaderName: 'X-XSRF-TOKEN',
  maxContentLength: -1,
  validateStatus: [Function: validateStatus],
  headers:
   { Accept: 'application/json',
     Authorization: 'Bearer 1.MVciNffaAPeD1GBAYb86JrAbACU=',
     'User-Agent': 'axios/0.16.2' },
  method: 'post',
  url: 'http://www14.v1host.com:80/v1sdktesting/query.v1',
  data: '{"from":"Story","select":["Name"]}' }
[]
```
https://github.com/mzabriskie/axios#response-schema describes `response.config` to contain information about the request.
My logging indicates that the method is a POST

**Comment by walkerrandolphsmith** [comment]
Is your instance running over TLS? https and the correct port can be used with the third and fourth parameters to the axios connector.

`const v1 = axiosConnectedSdk('www14.v1host.com', 'v1sdktesting', 443, true)`

**Comment by cookstaar** [comment]
Hey. Been tied up so didnt have chance to look at this before now. 

So if I look at response.config I do indeed see the same info as you 

```
Object {adapter: function httpAdapter(config) { … }, transformRequest: Object, transformResponse: Object …}
adapter:function httpAdapter(config) { … }
data:"{"from":"Story","select":["Name"]}"
headers:Object {Accept: "application/json", Content-Type: "application/json", Authorization: "Bearer 1.MVciNffaAPeD1GBAYb86JrAbACU=" …}
maxContentLength:-1
method:"post"
timeout:0
transformRequest:Object {0: function transformRequest(data, headers) { … }}
transformResponse:Object {0: function transformResponse(data) { … }}
url:"https://www14.v1host.com:443/v1sdktesting/query.v1"
```

HOWEVER, what I was looking at (which may be incorrect???) was response.request which showed an HTTP GET.

**DOUBLE HOWEVER**, when I add `, 443, true` to the connector, HEY PRESTO. It all works.

Problem 'solved' ;) However I still dont understand why I got the behaviour I saw when I first raised this issue......

**Comment by walkerrandolphsmith** [comment]
It is possible that a 304 redirect is happening when `POST`ing to http://host/instance and it drops the payload. If this is the case then `POST`ing to `query.v1` with no payload will respond with an empty set.

Try using your tool of choice to verify whether a 304 is the culprit.

**Comment by cookstaar** [comment]
Managed to work this out with your help above. Thanks for taking the time to help.
